language: python
python:
  - "3.8"

install:
  - python -m pip install --upgrade setuptools==70.0.0
  - python -m pip install -r requirements.txt
  - python -m pip install black flake8 coverage coveralls

script:
- black --check .
- flake8 --max-line-length=100 .
- coverage run manage.py test
- env

after_scripts:
- coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: "us-west-2"
  app: "django-env"
  env: "django-env"
  bucket_name: "elasticbeanstalk-us-west-2-557690601377"