language: python
python:
  - "3.8"

install:
  - pip install -r requirements.txt

script:
- black --check .
- flake8 --max-line-length=88 .
- coverage run manage.py test
- env

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: $aws-access-key
  secret_access_key:
    secure: $aws-secret-key
  region: "us-east-1"
  app: "example-app-name"
  env: "example-app-environment"
  bucket_name: "the-target-S3-bucket"